const lavatriciDatabase = [
    {
        id: 1,
        marca: "LG",
        modello: "F4X9009TWCE",
        serie: "Next AI DD 2025",
        capacita_kg: 9,
        classe_energetica: "A-60%",
        prezzo_min: 1300,
        prezzo_max: 1500,
        tipo_carica: "Frontale",
        funzione_vapore: "Sì",
        wifi: "Sì",
        auto_dosaggio: "Sì (Auto Dispenser)",
        ai: true,
        centrifuga_max: 1400,
        consumo_energia_kwh: 20,
        rumorosita_db: 72,
        tecnologie_principali: ["AI DD", "TurboWash 360", "Steam+"],
        dimensioni: "600x850x560",
        innovazioni: "A-60% record mondiale, 20 kWh/100 cicli"
    },
    {
        id: 2,
        marca: "LG",
        modello: "F4X7011TWB",
        serie: "Next AI DD X7",
        capacita_kg: 11,
        classe_energetica: "A-40%",
        prezzo_min: 1100,
        prezzo_max: 1300,
        tipo_carica: "Frontale",
        funzione_vapore: "Sì",
        wifi: "Sì",
        auto_dosaggio: "No",
        ai: true,
        centrifuga_max: 1400,
        consumo_energia_kwh: 30,
        rumorosita_db: 74,
        tecnologie_principali: ["AI DD", "Easy Circle Control"],
        dimensioni: "600x850x565",
        innovazioni: "11kg in dimensioni standard"
    },
    {
        id: 3,
        marca: "LG",
        modello: "F0P3020TSWC",
        serie: "P3 XL Commercial",
        capacita_kg: 20,
        classe_energetica: "A-10%",
        prezzo_min: 2000,
        prezzo_max: 2500,
        tipo_carica: "Frontale",
        funzione_vapore: "Sì",
        wifi: "Sì",
        auto_dosaggio: "No",
        ai: true,
        centrifuga_max: 1200,
        consumo_energia_kwh: 85,
        rumorosita_db: 78,
        tecnologie_principali: ["AI DD", "TurboWash 360", "Volume 142L"],
        dimensioni: "700x950x700",
        innovazioni: "Prima 20kg consumer ultra-capacity"
    },
    {
        id: 4,
        marca: "LG",
        modello: "F4R7010TSWG",
        serie: "R7",
        capacita_kg: 10,
        classe_energetica: "A-10%",
        prezzo_min: 600,
        prezzo_max: 700,
        tipo_carica: "Frontale",
        funzione_vapore: "Sì",
        wifi: "Sì",
        auto_dosaggio: "No",
        ai: true,
        centrifuga_max: 1400,
        consumo_energia_kwh: 47,
        rumorosita_db: 71,
        tecnologie_principali: ["AI DD", "Steam", "Direct Drive"],
        dimensioni: "600x850x565",
        innovazioni: "Motore Direct Drive 10 anni garanzia"
    },
    {
        id: 5,
        marca: "Bosch",
        modello: "WGB254A1IT",
        serie: "Serie 8",
        capacita_kg: 10,
        classe_energetica: "A-40%",
        prezzo_min: 1200,
        prezzo_max: 1400,
        tipo_carica: "Frontale",
        funzione_vapore: "Sì",
        wifi: "Sì",
        auto_dosaggio: "Sì (i-DOS intelligente)",
        ai: false,
        centrifuga_max: 1400,
        consumo_energia_kwh: 30,
        rumorosita_db: 68,
        tecnologie_principali: ["i-DOS", "Iron Assist", "Home Connect"],
        dimensioni: "598x845x590",
        innovazioni: "i-DOS dosaggio automatico riconoscimento detersivo"
    },
    {
        id: 6,
        marca: "Bosch",
        modello: "WGB24400IT",
        serie: "Serie 8",
        capacita_kg: 9,
        classe_energetica: "A-20%",
        prezzo_min: 1000,
        prezzo_max: 1200,
        tipo_carica: "Frontale",
        funzione_vapore: "Sì",
        wifi: "Sì",
        auto_dosaggio: "No",
        ai: false,
        centrifuga_max: 1400,
        consumo_energia_kwh: 40,
        rumorosita_db: 70,
        tecnologie_principali: ["Iron Assist", "4D Wash", "Home Connect"],
        dimensioni: "598x845x590",
        innovazioni: "Single Wash per singoli capi sostenibile"
    },
    {
        id: 7,
        marca: "Bosch",
        modello: "WGG244Z5IT",
        serie: "Serie 6",
        capacita_kg: 9,
        classe_energetica: "A",
        prezzo_min: 700,
        prezzo_max: 850,
        tipo_carica: "Frontale",
        funzione_vapore: "Sì",
        wifi: "No",
        auto_dosaggio: "No",
        ai: false,
        centrifuga_max: 1400,
        consumo_energia_kwh: 52,
        rumorosita_db: 72,
        tecnologie_principali: ["Iron Assist", "SpeedPerfect", "EcoSilence Drive"],
        dimensioni: "598x845x590",
        innovazioni: "AntiMacchia 4 macchie frequenti"
    },
    {
        id: 8,
        marca: "Bosch",
        modello: "WAN28299",
        serie: "Serie 4",
        capacita_kg: 8,
        classe_energetica: "A",
        prezzo_min: 600,
        prezzo_max: 750,
        tipo_carica: "Frontale",
        funzione_vapore: "Sì",
        wifi: "No",
        auto_dosaggio: "No",
        ai: false,
        centrifuga_max: 1400,
        consumo_energia_kwh: 55,
        rumorosita_db: 74,
        tecnologie_principali: ["Iron Assist", "ActiveWater Plus", "EcoSilence"],
        dimensioni: "598x845x590",
        innovazioni: "Entry-level Bosch con qualità tedesca"
    },
    {
        id: 9,
        marca: "Miele",
        modello: "WEK375 WPS",
        serie: "W1 Chrome Edition",
        capacita_kg: 9,
        classe_energetica: "A",
        prezzo_min: 1600,
        prezzo_max: 1800,
        tipo_carica: "Frontale",
        funzione_vapore: "Sì",
        wifi: "Sì",
        auto_dosaggio: "Sì (CapDosing)",
        ai: false,
        centrifuga_max: 1600,
        consumo_energia_kwh: 52,
        rumorosita_db: 68,
        tecnologie_principali: ["CapDosing", "QuickPowerWash", "Pre-Stiratura vapore"],
        dimensioni: "596x850x636",
        innovazioni: "Testata 20 anni, qualità tedesca premium"
    },
    {
        id: 10,
        marca: "Miele",
        modello: "WCK360 WCS",
        serie: "W1 Classic",
        capacita_kg: 10,
        classe_energetica: "A",
        prezzo_min: 1300,
        prezzo_max: 1500,
        tipo_carica: "Frontale",
        funzione_vapore: "Sì",
        wifi: "Sì",
        auto_dosaggio: "Sì (CapDosing)",
        ai: false,
        centrifuga_max: 1400,
        consumo_energia_kwh: 55,
        rumorosita_db: 70,
        tecnologie_principali: ["CapDosing", "QuickPowerWash", "Miele@home"],
        dimensioni: "596x850x636",
        innovazioni: "10kg Miele accessibile per famiglie numerose"
    },
    {
        id: 11,
        marca: "AEG",
        modello: "LR9H94GBS",
        serie: "9000 AbsoluteCare",
        capacita_kg: 9,
        classe_energetica: "A",
        prezzo_min: 1200,
        prezzo_max: 1500,
        tipo_carica: "Frontale",
        funzione_vapore: "Sì",
        wifi: "Sì",
        auto_dosaggio: "Sì (PowerCare)",
        ai: false,
        centrifuga_max: 1600,
        consumo_energia_kwh: 35,
        rumorosita_db: 67,
        tecnologie_principali: ["SoftWater", "AbsoluteCare", "PowerCare"],
        dimensioni: "597x847x636",
        innovazioni: "SoftWater unica al mondo filtra minerali dannosi"
    },
    {
        id: 12,
        marca: "Beko",
        modello: "WTY91436SI",
        serie: "SteamCure Premium",
        capacita_kg: 9,
        classe_energetica: "A",
        prezzo_min: 750,
        prezzo_max: 950,
        tipo_carica: "Frontale",
        funzione_vapore: "Sì",
        wifi: "Sì",
        auto_dosaggio: "No",
        ai: false,
        centrifuga_max: 1400,
        consumo_energia_kwh: 50,
        rumorosita_db: 73,
        tecnologie_principali: ["SteamCure 3-in-1", "StainExpert", "Pet Hair Removal"],
        dimensioni: "600x845x580",
        innovazioni: "SteamCure 3-in-1: antibatterico + antimacchia + antipiega"
    }
];