const lavatriciDatabase = [
    {
        id: 1,
        marca: "LG",
        modello: "F4X9009TWCE",
        serie: "Next AI DD 2025",
        capacita_kg: 9,
        classe_energetica: "A-60%",
        prezzo_min: 1300,
        prezzo_max: 1500,
        tipo_carica: "Frontale",
        funzione_vapore: "Sì",
        wifi: "Sì",
        auto_dosaggio: "Sì (Auto Dispenser)",
        ai: true,
        centrifuga_max: 1400,
        consumo_energia_kwh: 20,
        rumorosita_db: 72,
        tecnologie_principali: ["AI DD", "TurboWash 360", "Steam+"],
        dimensioni: "600x850x560",
        innovazioni: "A-60% record mondiale, 20 kWh/100 cicli",
        numero_programmi_totali: 14,
        durata_minima_minuti: 15,
        durata_massima_minuti: 240,
        risciacqui_massimi: 6,
        programmi_dettaglio: {
            "eco_40_60": { "nome": "ECO 40-60°C", "carico_massimo_kg": 9, "durata_minuti": 210, "numero_risciacqui": 3, "temperatura_range": "40-60°C", "tipo": "eco" },
            "ai_wash": { "nome": "AI Wash", "carico_massimo_kg": 9, "durata_minuti": 120, "numero_risciacqui": 4, "temperatura_range": "Automatico", "tipo": "auto" },
            "turbo_wash": { "nome": "TurboWash 39'", "carico_massimo_kg": 9, "durata_minuti": 39, "numero_risciacqui": 3, "temperatura_range": "40°C", "tipo": "turbo" },
            "baby_care": { "nome": "Baby Care", "carico_massimo_kg": 4, "durata_minuti": 120, "numero_risciacqui": 6, "temperatura_range": "60°C", "tipo": "igienizzante" },
            "rapido_15": { "nome": "Rapido 15'", "carico_massimo_kg": 2, "durata_minuti": 15, "numero_risciacqui": 2, "temperatura_range": "30°C", "tipo": "rapido" }
        }
    },
    {
        id: 2,
        marca: "LG",
        modello: "F4X7011TWB",
        serie: "Next AI DD X7",
        capacita_kg: 11,
        classe_energetica: "A-40%",
        prezzo_min: 1100,
        prezzo_max: 1300,
        tipo_carica: "Frontale",
        funzione_vapore: "Sì",
        wifi: "Sì",
        auto_dosaggio: "No",
        ai: true,
        centrifuga_max: 1400,
        consumo_energia_kwh: 30,
        rumorosita_db: 74,
        tecnologie_principali: ["AI DD", "Easy Circle Control"],
        dimensioni: "600x850x565",
        innovazioni: "11kg in dimensioni standard",
        numero_programmi_totali: 12,
        durata_minima_minuti: 14,
        durata_massima_minuti: 210,
        risciacqui_massimi: 5,
        programmi_dettaglio: {
            "eco_40_60": { "nome": "ECO 40-60°C", "carico_massimo_kg": 11, "durata_minuti": 210, "numero_risciacqui": 3, "temperatura_range": "40-60°C", "tipo": "eco" },
            "cotone": { "nome": "Cotone", "carico_massimo_kg": 11, "durata_minuti": 150, "numero_risciacqui": 3, "temperatura_range": "20-95°C", "tipo": "standard" },
            "turbo_wash": { "nome": "TurboWash 39'", "carico_massimo_kg": 11, "durata_minuti": 39, "numero_risciacqui": 3, "temperatura_range": "40°C", "tipo": "turbo" },
            "rapido_14": { "nome": "Rapido 14'", "carico_massimo_kg": 2, "durata_minuti": 14, "numero_risciacqui": 2, "temperatura_range": "30°C", "tipo": "rapido" },
            "allergy_care": { "nome": "Allergy Care", "carico_massimo_kg": 6, "durata_minuti": 120, "numero_risciacqui": 5, "temperatura_range": "60°C", "tipo": "igienizzante" }
        }
    },
    // ... (INSERISCI QUI IL RESTO DEI DATI DAL TUO FILE)
    {
        id: 11,
        marca: "AEG",
        modello: "LR9H94GBS",
        serie: "9000 AbsoluteCare",
        capacita_kg: 9,
        classe_energetica: "A",
        prezzo_min: 1200,
        prezzo_max: 1500,
        tipo_carica: "Frontale",
        funzione_vapore: "Sì",
        wifi: "Sì",
        auto_dosaggio: "Sì (PowerCare)",
        ai: false,
        centrifuga_max: 1600,
        consumo_energia_kwh: 35,
        rumorosita_db: 67,
        tecnologie_principali: ["SoftWater", "AbsoluteCare", "PowerCare"],
        dimensioni: "597x847x636",
        innovazioni: "SoftWater unica al mondo filtra minerali dannosi",
        numero_programmi_totali: 18,
        durata_minima_minuti: 15,
        durata_massima_minuti: 210,
        risciacqui_massimi: 5,
        programmi_dettaglio: {
            "eco_40_60": { "nome": "ECO 40-60°C", "carico_massimo_kg": 9, "durata_minuti": 210, "numero_risciacqui": 3, "temperatura_range": "40-60°C", "tipo": "eco" },
            "absolutewash": { "nome": "AbsoluteWash 49'", "carico_massimo_kg": 9, "durata_minuti": 49, "numero_risciacqui": 3, "temperatura_range": "30°C", "tipo": "turbo" },
            "prosense_auto": { "nome": "ProSense Auto", "carico_massimo_kg": 9, "durata_minuti": 120, "numero_risciacqui": 4, "temperatura_range": "Automatico", "tipo": "auto" },
            "refresh_15": { "nome": "Refresh 15'", "carico_massimo_kg": 2, "durata_minuti": 15, "numero_risciacqui": 2, "temperatura_range": "20°C", "tipo": "rapido" },
            "outdoor": { "nome": "Outdoor", "carico_massimo_kg": 4, "durata_minuti": 60, "numero_risciacqui": 5, "temperatura_range": "30°C", "tipo": "speciale" }
        }
    },
    {
        id: 12,
        marca: "Beko",
        modello: "WTY91436SI",
        serie: "SteamCure Premium",
        capacita_kg: 9,
        classe_energetica: "A",
        prezzo_min: 750,
        prezzo_max: 950,
        tipo_carica: "Frontale",
        funzione_vapore: "Sì",
        wifi: "Sì",
        auto_dosaggio: "No",
        ai: false,
        centrifuga_max: 1400,
        consumo_energia_kwh: 50,
        rumorosita_db: 73,
        tecnologie_principali: ["SteamCure 3-in-1", "StainExpert", "Pet Hair Removal"],
        dimensioni: "600x845x580",
        innovazioni: "SteamCure 3-in-1: antibatterico + antimacchia + antipiega",
        numero_programmi_totali: 16,
        durata_minima_minuti: 14,
        durata_massima_minuti: 210,
        risciacqui_massimi: 5,
        programmi_dettaglio: {
            "eco_40_60": { "nome": "ECO 40-60°C", "carico_massimo_kg": 9, "durata_minuti": 210, "numero_risciacqui": 3, "temperatura_range": "40-60°C", "tipo": "eco" },
            "steamcure": { "nome": "SteamCure 3-in-1", "carico_massimo_kg": 7, "durata_minuti": 90, "numero_risciacqui": 4, "temperatura_range": "60°C", "tipo": "vapore" },
            "daily_xpress": { "nome": "Daily Xpress 28'", "carico_massimo_kg": 9, "durata_minuti": 28, "numero_risciacqui": 3, "temperatura_range": "30°C", "tipo": "turbo" },
            "super_xpress": { "nome": "Super Xpress 14'", "carico_massimo_kg": 2, "durata_minuti": 14, "numero_risciacqui": 2, "temperatura_range": "30°C", "tipo": "rapido" },
            "pet_hair_removal": { "nome": "Pet Hair Removal", "carico_massimo_kg": 6, "durata_minuti": 120, "numero_risciacqui": 5, "temperatura_range": "40°C", "tipo": "speciale" }
        }
    }
];